### ISSUE TITLE
Second Run Of Elm-Analyse is broken 

### ISSUE THREAD

**Issue by gogocurtis** [stil4m/elm-analyse#132]
Second run of elm-analyse@0.13.1 results in the following crash

```
undefined:1
Processing multiple files...
^

SyntaxError: Unexpected token P in JSON at position 0
    at JSON.parse (<anonymous>)
    at setupCache (/usr/local/lib/node_modules/elm-analyse/js/util/format-service.js:49:39)
```
in my case I have patched format service
```
        } catch (e) {
            // Parse Std [1]
             try {
            const invalidFiles = JSON.parse(e.output[1].toString());
            invalidFiles.forEach(f => {
                cache[f.path] = false;
            });
             } catch (ej) {
                console.log(e.output[1].toString())

                }
        }
```
in my case  e.output[1].toString() is not json.

It is: 
File would be changed /Users/curtis/Dev/elm-spike/elm-stuff/.elm-analyse/_shas/099b1e4d7d73a905e2c0b7ff47a32edb3734c3ef.elma

**Comment by stil4m** [comment]
Thanks for your report. Much appreciated.

Which version of elm-format are you using?

I believe 0.6 and up supports JSON output when a path is validated. elm-analyse uses that JSON output. If you are using 0.5 at the moment that would explain the issue. Still, this needs to be fixed.

**Comment by jarcane** [comment]
Having the same bug. Elm-analyse 0.13.2, elm-format-0.18 0.6.1-alpha.

```
Fetching package information from package.elm-lang.org.
Fetched dependencies
undefined:1
[There was a problem reading one or more of the specified input files:
 ^

SyntaxError: Unexpected token T in JSON at position 1
    at JSON.parse (<anonymous>)
    at setupCache (C:\Users\<redacted>\AppData\Roaming\npm\node_modules\elm-analyse\js\util\format-service.js:48:39)
    at module.exports (C:\Users\<redacted>\AppData\Roaming\npm\node_modules\elm-analyse\js\util\format-service.js:56:5)
    at module.exports (C:\Users\<redacted>\AppData\Roaming\npm\node_modules\elm-analyse\js\fileReader.js:8:59)
    at module.exports (C:\Users\<redacted>\AppData\Roaming\npm\node_modules\elm-analyse\js\util\file-loading-ports.js:8:48)
    at C:\Users\<redacted>\AppData\Roaming\npm\node_modules\elm-analyse\js\analyser.js:22:9
    at C:\Users\<redacted>\AppData\Roaming\npm\node_modules\elm-analyse\js\util\dependencies.js:34:9
    at Request._callback (C:\Users\<redacted>\AppData\Roaming\npm\node_modules\elm-analyse\js\util\dependencies.js:19:9)
    at Request.self.callback (C:\Users\<redacted>\AppData\Roaming\npm\node_modules\elm-analyse\node_modules\request\request.js:186:22)
    at emitTwo (events.js:125:13)
```

**Comment by stil4m** [comment]
Found the issue and fixed it. Will release it later today in `0.13.3`. Thanks for your bug report!

**Comment by jarcane** [comment]
Thanks. I still get the same error but it runs now. I'm also getting an error with the server mode complaining that "./tests is missing" but I just made an empty directory and that went away.

**Comment by stil4m** [comment]
@jarcane. Hi Jarcane. Great that is working now. Can you create an issue for the error you encountered? Could you provide the (anonymised) `elm-package.json` and the folder structure (CLI `ls` or `dir`) that allows me to reproduce the issue? Thanks.

**Comment by jarcane** [comment]
Sure, I'll take a look and see what I can do next week.

**Comment by jarcane** [comment]
After looking at my elm-package, I think actually the error was because of an extra dir in my config and not elm-analyse' fault.
