### ISSUE TITLE
elm-analyse -s errors on truqu/base64

### ISSUE THREAD

**Issue by mordrax** [stil4m/elm-analyse#175]
I just ran `elm-analyse -s` and got the following, it seems to be failing on this package `"truqu/elm-base64": "2.0.3 <= v < 3.0.0"`. Running it without the `-s` server option has gone past the error and is processing each file :

```
Elm Analyser server starting with config:
{ port: '4000',
  elmFormatPath: 'elm-format',
  format: 'human',
  open: false }
Listening on http://localhost:4000
INFO: No configuration provided. Using default configuration.
INFO: Load dependency truqu/elm-base64 2.0.3
INFO: Load dependency terezka/elm-plot 5.1.0
INFO: Load dependency mgold/elm-random-pcg 4.0.2
INFO: Load dependency lukewestby/elm-http-builder 5.2.0
INFO: Load dependency evancz/url-parser 2.0.1
INFO: Load dependency elm-lang/virtual-dom 2.0.4
INFO: Load dependency elm-lang/svg 2.0.0
INFO: Load dependency elm-lang/navigation 2.1.0
INFO: Load dependency elm-lang/keyboard 1.0.1
INFO: Load dependency elm-lang/http 1.0.0
INFO: Load dependency elm-lang/html 2.0.0
INFO: Load dependency elm-lang/dom 1.1.1
INFO: Load dependency elm-lang/core 5.1.1
INFO: Load dependency elm-community/string-extra 1.5.0
INFO: Load dependency elm-community/result-extra 2.2.0
INFO: Load dependency elm-community/maybe-extra 4.0.0
INFO: Load dependency elm-community/list-extra 4.0.0
INFO: Load dependency elm-community/elm-time 1.0.14
INFO: Load dependency eeue56/elm-all-dict 2.0.1
INFO: Load dependency debois/elm-dom 1.2.3
INFO: Load dependency cuducos/elm-format-number 5.0.5
INFO: Load dependency billstclair/elm-localstorage 4.0.2
INFO: Load dependency NoRedInk/elm-decode-pipeline 3.0.1
fs.js:1384
    throw error;
    ^

Error: watch elm-stuff/build-artifacts/0.18.0/truqu ENOSPC
    at _errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at /usr/local/lib/node_modules/elm-analyse/node_modules/node-watch/lib/watch.js:312:22
    at hasNativeRecursive (/usr/local/lib/node_modules/elm-analyse/node_modules/node-watch/lib/has-native-recursive.js:61:12)
    at Watcher.watchDirectory (/usr/local/lib/node_modules/elm-analyse/node_modules/node-watch/lib/watch.js:301:3)
    at /usr/local/lib/node_modules/elm-analyse/node_modules/node-watch/lib/watch.js:329:16
    at /usr/local/lib/node_modules/elm-analyse/node_modules/node-watch/lib/watch.js:69:7
    at /usr/local/lib/node_modules/elm-analyse/node_modules/node-watch/lib/watch.js:328:9
    at /usr/local/lib/node_modules/elm-analyse/node_modules/node-watch/lib/watch.js:152:35
```

**Comment by mordrax** [comment]
Extra info: `elm-analyse -s` works for me on my mac and the above was done on my ubuntu 18.04 ( bionic bever) which leads me to think that this is more related to fsevents warnings that I get on the ubuntu box and unrelated to elm-analyse or ubuntu.
