### ISSUE TITLE
Websocket connection error

### ISSUE THREAD

**Issue by hakonrossebo** [stil4m/elm-analyse#84]
While testing vscode-elm websocket against elm-analyse, I get this exception/stack trace when saving files (after initial ws connection). I have only observed this on Windows so far (Much faster on Linux). At the same time it also seems to restart the socket connection (I have a message showing up on the "open" event).
This could possibly be related to my ws implementation.

```

C:\Users\username\AppData\Roaming\npm\node_modules\elm-analyse\node_modules\ws\lib\WebSocket.js:219
    else throw new Error('not opened');
         ^

Error: not opened
    at WebSocket.send (C:\Users\username\AppData\Roaming\npm\node_modules\elm-analyse\node_modules\ws\lib\WebSocket.js:219:16)
    at expressWs.getWss.clients.forEach.x (C:\Users\username\AppData\Roaming\npm\node_modules\elm-analyse\js\server\dashboard.js:22:51)
    at Array.forEach (native)
    at Array.<anonymous> (C:\Users\username\AppData\Roaming\npm\node_modules\elm-analyse\js\server\dashboard.js:22:36)
    at Function.onEffects [as func] (C:\Users\username\AppData\Roaming\npm\node_modules\elm-analyse\js\backend-elm.js:2706:19)
    at A3 (C:\Users\username\AppData\Roaming\npm\node_modules\elm-analyse\js\backend-elm.js:98:11)
    at onMessage (C:\Users\username\AppData\Roaming\npm\node_modules\elm-analyse\js\backend-elm.js:2489:12)
    at Object.callback (C:\Users\username\AppData\Roaming\npm\node_modules\elm-analyse\js\backend-elm.js:2531:11)
    at step (C:\Users\username\AppData\Roaming\npm\node_modules\elm-analyse\js\backend-elm.js:3068:32)
    at Timeout.work [as _onTimeout] (C:\Users\username\AppData\Roaming\npm\node_modules\elm-analyse\js\backend-elm.js:3110:15)
```

**Comment by stil4m** [comment]
It seems that the server wants to send something on a socket which is in a invalid state. This is an `elm-analyse` issue and should gracefully handled. 

Can you investigate why the connection is closed?

**Comment by hakonrossebo** [comment]
Fixed this issue on the client side - had some event starting the websocket multiple times. Ok to close issue.

**Comment by stil4m** [comment]
I'll leave it open because the server should handle it gracefully. The fix will be an easy try catch with some logging.
